# Copyright © 2018 Po Huit
# [This program is licensed under the "MIT License"]
# Please see the file LICENSE in the source
# distribution of this software for license terms.

[package]
name = "web"
version = "0.1.0"
authors = ["Po Huit <eve.po.huit@gmail.com>"]

[dependencies]
plan_b = {path = "../plan_b"}
rocket = "0.3.9"
rocket_codegen = "0.3.9"

[[bin]]
name = "plan-b-web"
path = "src/main.rs"
